title: "Jackson's Tech World"
name: "Jackson's Tech World"
description: "A deep dive into systems programming, C++, and performance optimization. Exploring the foundations of computing one post at a time."
tagline: "Exploring Tech, One Algorithm at a Time"
author: "Jackson R"
email: "contact@jacksonstechworld.dev"

# SEO and metadata
meta_description: "Jackson R's technical blog covering systems programming, C++, performance optimization, and low-level computing concepts."
keywords: "C++, systems programming, performance optimization, assembly, algorithms, software engineering"

# Social links
github_username: spi3ex
twitter_username: # Add if you have one
linkedin_username: # Add if you have one

# Build settings
markdown: kramdown
highlighter: rouge
logo: false
baseurl: "" 
url: "https://spi3ex.github.io"
permalink: /:categories/:year/:y_day/:title/

# Analytics (uncomment and add your tracking ID)
#google_analytics: "UA-XXXXXXXX-X"

# Plugins (GitHub Pages compatible)
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings (GitHub Pages compatible)
paginate: 5
paginate_path: "/page:num/"

# Feed configuration
feed:
  path: feed.xml
  excerpt_only: false

# Comments (Disqus)
disqus-shortname: ""

# Reading time estimation
reading_time: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jackson R"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
