title: "Jackson's Tech World"
name: "Jackson's Tech World"
description: "Embedded Systems, Android Platform Development, and Open-Source Contributions. Exploring low-level programming and system software development."
tagline: "Embedded Systems & Platform Software Engineer"
author: "Jackson R"
email: "hellojackson.r@gmail.com"

# SEO and metadata
meta_description: "Jackson R's technical blog covering embedded systems, Android platform development, C/C++ programming, and open-source contributions. Currently working as Embedded Software Engineer at L&T Technology Services."
keywords: "embedded systems, Android platform, C++, C programming, AOSP, device drivers, RTOS, system software, open source"

# Social links
github_username: spi3ex
linkedin_username: spi3ex
# twitter_username: # Add if you have one

# Build settings
markdown: kramdown
highlighter: rouge
logo: false
baseurl: "" 
url: "https://spi3ex.github.io"
permalink: /:categories/:year/:y_day/:title/

# Analytics (uncomment and add your tracking ID)
#google_analytics: "UA-XXXXXXXX-X"

# Plugins (GitHub Pages compatible)
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings (GitHub Pages compatible)
paginate: 5
paginate_path: "/page:num/"

# Feed configuration
feed:
  path: feed.xml
  excerpt_only: false

# Comments (Disqus)
disqus-shortname: ""

# Reading time estimation
reading_time: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jackson R"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
